-   id: pngquant
    name: oxipng
    description: 'Lossy compression of PNG images using pngquant'
    entry: pngquant-wrapper.sh
    language: script
    types: [png]
    require_serial: true
    pass_filenames: true
